#core:
    #resource: "@CoreBundle/Resources/config/routing.yml"
    #prefix:   /

a2_user:
    resource: "@A2UserBundle/Resources/config/routing.yml"
    #prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"