<?php

namespace A2\CustomerBundle\Repository;
use A2\CustomerBundle\Entity\Customer;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFind($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->andWhere('c.isActive = :isActive')
            ->setParameter('isActive', 1)
        ;

        return $qb
            ->getQuery()
            ->getSingleResult()
        ;
    }

    public function myRemove($id)
    {
        $customer = $this->myFind($id);
        $customer->setIsActive(false);

        return;
    }

    public function getAdminName(Customer $customer, $action)
    {
        $query = $this->_em->createQuery('SELECT u.name, u.lastname FROM A2UserBundle:User u WHERE u.id = :id');

        if ($action == 'add')
            $query->setParameter('id', $customer->getAdminAdd());
        else
            $query->setParameter('id', $customer->getUserUpdate());

        $name = "";
        $results = $query->getArrayResult();
        foreach ($results as $result)
        {
            $name = $result['name'];
            $name .= ' ' .$result['lastname'];
        }

        return $name;
    }

    public function findByKeyword($keyword)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->where('c.name LIKE \'%'. $keyword .'%\'')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}