<?php

namespace A2\StorehouseBundle\Repository;

/**
 * StorehouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorehouseRepository extends \Doctrine\ORM\EntityRepository
{
}
