a2_stock_index:
    path:            /
    defaults:
        _controller: A2StockBundle:Stock:index
    methods:         [GET, POST]

a2_stock_show:
    path:            /{id}/show
    defaults:
        _controller: A2StockBundle:Stock:show
    requirements:
        id:          \d+
    methods:         GET

a2_stock_delete:
    path:            /{id}/delete
    defaults:
        _controller: A2StockBundle:Stock:delete
    requirements:
        id:          \d+
    methods:         [GET, POST]