<?php

namespace A2\CategoryBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->where('c.isActive = :isActive')
            ->setParameter('isActive', 1)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function myFind($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->andWhere('c.isActive = :isActive')
            ->setParameter('isActive', 1)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function myRemove($id)
    {
        $category = $this->myFind($id);
        $category->setIsActive(false);

        return;
    }
}