<?php

namespace A2\CategoryBundle\Repository;
use A2\CategoryBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFind($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->andWhere('c.isActive = :isActive')
            ->setParameter('isActive', 1)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function myRemove($id)
    {
        $category = $this->myFind($id);
        $category->setIsActive(false);

        return;
    }

    public function getAdminName(Category $category, $action)
    {
        $query = $this->_em->createQuery('SELECT u.usrName, u.userLastName FROM A2UserBundle:User u WHERE u.id = :id');

        if ($action == 'add')
            $query->setParameter('id', $category->getAdminAdd());
        else
            $query->setParameter('id', $category->getUserUpdate());

        $name = "";
        $results = $query->getArrayResult();
        foreach ($results as $result)
        {
            $name = $result['usrName'];
            $name .= ' ' .$result['userLastName'];
        }

        return $name;
    }
}